create table cadastrar (documentos_id number(19,0), id number(19,0) generated as identity, usuario_id number(19,0), email varchar2(255 char), nome_usuario varchar2(255 char), senha varchar2(255 char), primary key (id));
create table cadastrar_cnpj (id number(19,0) generated as identity, cnpj varchar2(255 char), razao_social varchar2(255 char), primary key (id));
create table contato (id number(19,0) generated as identity, celular varchar2(255 char), email_alternativo varchar2(255 char), telefone varchar2(255 char), primary key (id));
create table documentos (id number(19,0) generated as identity, cpf varchar2(255 char), rg varchar2(255 char), primary key (id));
create table endereco (numero number(10,0) not null check (numero>=1), id number(19,0) generated as identity, bairro varchar2(255 char), cep varchar2(255 char), cidade varchar2(255 char), complemento varchar2(255 char), estado varchar2(255 char), logradouro varchar2(255 char), primary key (id));
create table esqueci_senha (id number(19,0) generated as identity, codigo_recuperacao varchar2(255 char), email varchar2(255 char), nova_senha varchar2(255 char), primary key (id));
create table eventos (data_hora timestamp(6), id number(19,0) generated as identity, localizacao_id number(19,0) unique, organizador_id number(19,0), ponto_coleta_id number(19,0) unique, descricao varchar2(255 char), nome varchar2(255 char), primary key (id));
create table eventos_participantes (eventos_id number(19,0) not null, participantes_id number(19,0) not null);
create table localizacao (id number(19,0) generated as identity, reportado_em timestamp(6), reportado_por_id number(19,0), descricao varchar2(255 char), endereco varchar2(255 char), referencia varchar2(255 char), url_foto varchar2(255 char), primary key (id));
create table login (cadastrar_id number(19,0) unique, esqueci_senha_id number(19,0) unique, id number(19,0) generated as identity, login_apple_id number(19,0) unique, login_google_id number(19,0) unique, nome_usuario varchar2(255 char), senha varchar2(255 char), primary key (id));
create table login_apple (id number(19,0) generated as identity, apple_id varchar2(255 char), token varchar2(255 char), primary key (id));
create table login_google (id number(19,0) generated as identity, google_id varchar2(255 char), token varchar2(255 char), primary key (id));
create table ponto_coleta (id number(19,0) generated as identity, contato varchar2(255 char), descricao varchar2(255 char), horario_funcionamento varchar2(255 char), nome varchar2(255 char), primary key (id));
create table relatorio_poluicao (criado_em timestamp(6), id number(19,0) generated as identity, localizacao_id number(19,0) unique, tipo_poluicao varchar2(255 char), primary key (id));
create table usuario (id number(19,0) generated as identity, nome_completo varchar2(255 char), primary key (id));
alter table cadastrar add constraint FKlmhb8m9e1kma6ar0orkse7mgf foreign key (documentos_id) references documentos;
alter table cadastrar add constraint FKmw461iwrvbxtsrhi6ges50j07 foreign key (usuario_id) references usuario;
alter table eventos add constraint FKpvjmg96ol6rh3wxmwg776v6au foreign key (localizacao_id) references localizacao;
alter table eventos add constraint FKh1h7x29wfjquom85fq8pipfxo foreign key (organizador_id) references usuario;
alter table eventos add constraint FKgkipisolbv8t34m08gbdgautc foreign key (ponto_coleta_id) references ponto_coleta;
alter table eventos_participantes add constraint FKaexl8grwnwo4k6yobtgk5h0rf foreign key (participantes_id) references usuario;
alter table eventos_participantes add constraint FKq7ep0f3cniv1k80j3tm9dk4d foreign key (eventos_id) references eventos;
alter table localizacao add constraint FKf7pcd0wjkqieljs48w1pmgifi foreign key (reportado_por_id) references usuario;
alter table login add constraint FKdjkhg132oavpve1w1kuua6fq foreign key (cadastrar_id) references cadastrar;
alter table login add constraint FKc7cfh2n8udej2qk26ede1cnrd foreign key (esqueci_senha_id) references esqueci_senha;
alter table login add constraint FKdgq882cqtbpl9uqn3v2yq4n02 foreign key (login_apple_id) references login_apple;
alter table login add constraint FKrchmtuwp6pkh4sj2fcyvfy8om foreign key (login_google_id) references login_google;
alter table relatorio_poluicao add constraint FKi3ok2canbtysxg6oobfhtf9ai foreign key (localizacao_id) references localizacao;
create table cadastrar (documentos_id number(19,0), id number(19,0) generated as identity, usuario_id number(19,0), email varchar2(255 char), nome_usuario varchar2(255 char), senha varchar2(255 char), primary key (id));
create table cadastrar_cnpj (id number(19,0) generated as identity, cnpj varchar2(255 char), razao_social varchar2(255 char), primary key (id));
create table contato (id number(19,0) generated as identity, celular varchar2(255 char), email_alternativo varchar2(255 char), telefone varchar2(255 char), primary key (id));
create table endereco (numero number(10,0) not null check (numero>=1), id number(19,0) generated as identity, bairro varchar2(255 char), cep varchar2(255 char), cidade varchar2(255 char), complemento varchar2(255 char), estado varchar2(255 char), logradouro varchar2(255 char), primary key (id));
create table esqueci_senha (id number(19,0) generated as identity, codigo_recuperacao varchar2(255 char), email varchar2(255 char), nova_senha varchar2(255 char), primary key (id));
create table eventos (data_hora timestamp(6), id number(19,0) generated as identity, localizacao_id number(19,0) unique, organizador_id number(19,0), ponto_coleta_id number(19,0) unique, descricao varchar2(255 char), nome varchar2(255 char), primary key (id));
create table eventos_participantes (eventos_id number(19,0) not null, participantes_id number(19,0) not null);
create table localizacao (id number(19,0) generated as identity, reportado_em timestamp(6), reportado_por_id number(19,0), descricao varchar2(255 char), endereco varchar2(255 char), referencia varchar2(255 char), url_foto varchar2(255 char), primary key (id));
create table login (cadastrar_id number(19,0) unique, esqueci_senha_id number(19,0) unique, id number(19,0) generated as identity, login_apple_id number(19,0) unique, login_google_id number(19,0) unique, nome_usuario varchar2(255 char), senha varchar2(255 char), primary key (id));
create table login_apple (id number(19,0) generated as identity, apple_id varchar2(255 char), token varchar2(255 char), primary key (id));
create table login_google (id number(19,0) generated as identity, google_id varchar2(255 char), token varchar2(255 char), primary key (id));
create table ponto_coleta (id number(19,0) generated as identity, contato varchar2(255 char), descricao varchar2(255 char), horario_funcionamento varchar2(255 char), nome varchar2(255 char), primary key (id));
create table relatorio_poluicao (criado_em timestamp(6), id number(19,0) generated as identity, localizacao_id number(19,0) unique, tipo_poluicao varchar2(255 char), primary key (id));
create table tb_documentos (id number(19,0) generated as identity, cpf varchar2(255 char), rg varchar2(255 char), primary key (id));
create table usuario (id number(19,0) generated as identity, nome_completo varchar2(255 char), primary key (id));
alter table cadastrar add constraint FKamt0upm8b7rhbixwxrjv4algj foreign key (documentos_id) references tb_documentos;
alter table cadastrar add constraint FKmw461iwrvbxtsrhi6ges50j07 foreign key (usuario_id) references usuario;
alter table eventos add constraint FKpvjmg96ol6rh3wxmwg776v6au foreign key (localizacao_id) references localizacao;
alter table eventos add constraint FKh1h7x29wfjquom85fq8pipfxo foreign key (organizador_id) references usuario;
alter table eventos add constraint FKgkipisolbv8t34m08gbdgautc foreign key (ponto_coleta_id) references ponto_coleta;
alter table eventos_participantes add constraint FKaexl8grwnwo4k6yobtgk5h0rf foreign key (participantes_id) references usuario;
alter table eventos_participantes add constraint FKq7ep0f3cniv1k80j3tm9dk4d foreign key (eventos_id) references eventos;
alter table localizacao add constraint FKf7pcd0wjkqieljs48w1pmgifi foreign key (reportado_por_id) references usuario;
alter table login add constraint FKdjkhg132oavpve1w1kuua6fq foreign key (cadastrar_id) references cadastrar;
alter table login add constraint FKc7cfh2n8udej2qk26ede1cnrd foreign key (esqueci_senha_id) references esqueci_senha;
alter table login add constraint FKdgq882cqtbpl9uqn3v2yq4n02 foreign key (login_apple_id) references login_apple;
alter table login add constraint FKrchmtuwp6pkh4sj2fcyvfy8om foreign key (login_google_id) references login_google;
alter table relatorio_poluicao add constraint FKi3ok2canbtysxg6oobfhtf9ai foreign key (localizacao_id) references localizacao;
create table cadastrar (documentos_id bigint, id bigint generated by default as identity, usuario_id bigint, email varchar(255), nome_usuario varchar(255), senha varchar(255), primary key (id));
create table cadastrar_cnpj (id bigint generated by default as identity, cnpj varchar(255), razao_social varchar(255), primary key (id));
create table contato (id bigint generated by default as identity, celular varchar(255), email_alternativo varchar(255), telefone varchar(255), primary key (id));
create table endereco (numero integer not null check (numero>=1), id bigint generated by default as identity, bairro varchar(255), cep varchar(255), cidade varchar(255), complemento varchar(255), estado varchar(255), logradouro varchar(255), primary key (id));
create table esqueci_senha (id bigint generated by default as identity, codigo_recuperacao varchar(255), email varchar(255), nova_senha varchar(255), primary key (id));
create table eventos (data_hora timestamp(6), id bigint generated by default as identity, localizacao_id bigint unique, organizador_id bigint, ponto_coleta_id bigint unique, descricao varchar(255), nome varchar(255), primary key (id));
create table eventos_participantes (eventos_id bigint not null, participantes_id bigint not null);
create table localizacao (id bigint generated by default as identity, reportado_em timestamp(6), reportado_por_id bigint, descricao varchar(255), endereco varchar(255), referencia varchar(255), url_foto varchar(255), primary key (id));
create table login (cadastrar_id bigint unique, esqueci_senha_id bigint unique, id bigint generated by default as identity, login_apple_id bigint unique, login_google_id bigint unique, nome_usuario varchar(255), senha varchar(255), primary key (id));
create table login_apple (id bigint generated by default as identity, apple_id varchar(255), token varchar(255), primary key (id));
create table login_google (id bigint generated by default as identity, google_id varchar(255), token varchar(255), primary key (id));
create table ponto_coleta (id bigint generated by default as identity, contato varchar(255), descricao varchar(255), horario_funcionamento varchar(255), nome varchar(255), primary key (id));
create table relatorio_poluicao (criado_em timestamp(6), id bigint generated by default as identity, localizacao_id bigint unique, tipo_poluicao varchar(255), primary key (id));
create table tb_documentos (id bigint generated by default as identity, cpf varchar(255), rg varchar(255), primary key (id));
create table usuario (id bigint generated by default as identity, nome_completo varchar(255), primary key (id));
alter table if exists cadastrar add constraint FKamt0upm8b7rhbixwxrjv4algj foreign key (documentos_id) references tb_documentos;
alter table if exists cadastrar add constraint FKmw461iwrvbxtsrhi6ges50j07 foreign key (usuario_id) references usuario;
alter table if exists eventos add constraint FKpvjmg96ol6rh3wxmwg776v6au foreign key (localizacao_id) references localizacao;
alter table if exists eventos add constraint FKh1h7x29wfjquom85fq8pipfxo foreign key (organizador_id) references usuario;
alter table if exists eventos add constraint FKgkipisolbv8t34m08gbdgautc foreign key (ponto_coleta_id) references ponto_coleta;
alter table if exists eventos_participantes add constraint FKaexl8grwnwo4k6yobtgk5h0rf foreign key (participantes_id) references usuario;
alter table if exists eventos_participantes add constraint FKq7ep0f3cniv1k80j3tm9dk4d foreign key (eventos_id) references eventos;
alter table if exists localizacao add constraint FKf7pcd0wjkqieljs48w1pmgifi foreign key (reportado_por_id) references usuario;
alter table if exists login add constraint FKdjkhg132oavpve1w1kuua6fq foreign key (cadastrar_id) references cadastrar;
alter table if exists login add constraint FKc7cfh2n8udej2qk26ede1cnrd foreign key (esqueci_senha_id) references esqueci_senha;
alter table if exists login add constraint FKdgq882cqtbpl9uqn3v2yq4n02 foreign key (login_apple_id) references login_apple;
alter table if exists login add constraint FKrchmtuwp6pkh4sj2fcyvfy8om foreign key (login_google_id) references login_google;
alter table if exists relatorio_poluicao add constraint FKi3ok2canbtysxg6oobfhtf9ai foreign key (localizacao_id) references localizacao;
create table cadastrar (documentos_id bigint, id bigint generated by default as identity, usuario_id bigint, email varchar(255), nome_usuario varchar(255), senha varchar(255), primary key (id));
create table cadastrar_cnpj (id bigint generated by default as identity, cnpj varchar(255), razao_social varchar(255), primary key (id));
create table contato (id bigint generated by default as identity, celular varchar(255), email_alternativo varchar(255), telefone varchar(255), primary key (id));
create table endereco (numero integer not null check (numero>=1), id bigint generated by default as identity, bairro varchar(255), cep varchar(255), cidade varchar(255), complemento varchar(255), estado varchar(255), logradouro varchar(255), primary key (id));
create table esqueci_senha (id bigint generated by default as identity, codigo_recuperacao varchar(255), email varchar(255), nova_senha varchar(255), primary key (id));
create table eventos (data_hora timestamp(6), id bigint generated by default as identity, localizacao_id bigint unique, organizador_id bigint, ponto_coleta_id bigint unique, descricao varchar(255), nome varchar(255), primary key (id));
create table eventos_participantes (eventos_id bigint not null, participantes_id bigint not null);
create table localizacao (id bigint generated by default as identity, reportado_em timestamp(6), reportado_por_id bigint, descricao varchar(255), endereco varchar(255), referencia varchar(255), url_foto varchar(255), primary key (id));
create table login (cadastrar_id bigint unique, esqueci_senha_id bigint unique, id bigint generated by default as identity, login_apple_id bigint unique, login_google_id bigint unique, nome_usuario varchar(255), senha varchar(255), primary key (id));
create table login_apple (id bigint generated by default as identity, apple_id varchar(255), token varchar(255), primary key (id));
create table login_google (id bigint generated by default as identity, google_id varchar(255), token varchar(255), primary key (id));
create table ponto_coleta (id bigint generated by default as identity, contato varchar(255), descricao varchar(255), horario_funcionamento varchar(255), nome varchar(255), primary key (id));
create table relatorio_poluicao (criado_em timestamp(6), id bigint generated by default as identity, localizacao_id bigint unique, tipo_poluicao varchar(255), primary key (id));
create table tb_documentos (id bigint generated by default as identity, cpf varchar(255), rg varchar(255), primary key (id));
create table usuario (id bigint generated by default as identity, nome_completo varchar(255), primary key (id));
alter table if exists cadastrar add constraint FKamt0upm8b7rhbixwxrjv4algj foreign key (documentos_id) references tb_documentos;
alter table if exists cadastrar add constraint FKmw461iwrvbxtsrhi6ges50j07 foreign key (usuario_id) references usuario;
alter table if exists eventos add constraint FKpvjmg96ol6rh3wxmwg776v6au foreign key (localizacao_id) references localizacao;
alter table if exists eventos add constraint FKh1h7x29wfjquom85fq8pipfxo foreign key (organizador_id) references usuario;
alter table if exists eventos add constraint FKgkipisolbv8t34m08gbdgautc foreign key (ponto_coleta_id) references ponto_coleta;
alter table if exists eventos_participantes add constraint FKaexl8grwnwo4k6yobtgk5h0rf foreign key (participantes_id) references usuario;
alter table if exists eventos_participantes add constraint FKq7ep0f3cniv1k80j3tm9dk4d foreign key (eventos_id) references eventos;
alter table if exists localizacao add constraint FKf7pcd0wjkqieljs48w1pmgifi foreign key (reportado_por_id) references usuario;
alter table if exists login add constraint FKdjkhg132oavpve1w1kuua6fq foreign key (cadastrar_id) references cadastrar;
alter table if exists login add constraint FKc7cfh2n8udej2qk26ede1cnrd foreign key (esqueci_senha_id) references esqueci_senha;
alter table if exists login add constraint FKdgq882cqtbpl9uqn3v2yq4n02 foreign key (login_apple_id) references login_apple;
alter table if exists login add constraint FKrchmtuwp6pkh4sj2fcyvfy8om foreign key (login_google_id) references login_google;
alter table if exists relatorio_poluicao add constraint FKi3ok2canbtysxg6oobfhtf9ai foreign key (localizacao_id) references localizacao;
create table cadastrar (documentos_id bigint, id bigint generated by default as identity, usuario_id bigint, email varchar(255), nome_usuario varchar(255), senha varchar(255), primary key (id));
create table cadastrar_cnpj (id bigint generated by default as identity, cnpj varchar(255), razao_social varchar(255), primary key (id));
create table contato (id bigint generated by default as identity, celular varchar(255), email_alternativo varchar(255), telefone varchar(255), primary key (id));
create table endereco (numero integer not null check (numero>=1), id bigint generated by default as identity, bairro varchar(255), cep varchar(255), cidade varchar(255), complemento varchar(255), estado varchar(255), logradouro varchar(255), primary key (id));
create table esqueci_senha (id bigint generated by default as identity, codigo_recuperacao varchar(255), email varchar(255), nova_senha varchar(255), primary key (id));
create table eventos (data_hora timestamp(6), id bigint generated by default as identity, localizacao_id bigint unique, organizador_id bigint, ponto_coleta_id bigint unique, descricao varchar(255), nome varchar(255), primary key (id));
create table eventos_participantes (eventos_id bigint not null, participantes_id bigint not null);
create table localizacao (id bigint generated by default as identity, reportado_em timestamp(6), reportado_por_id bigint, descricao varchar(255), endereco varchar(255), referencia varchar(255), url_foto varchar(255), primary key (id));
create table login (cadastrar_id bigint unique, esqueci_senha_id bigint unique, id bigint generated by default as identity, login_apple_id bigint unique, login_google_id bigint unique, nome_usuario varchar(255), senha varchar(255), primary key (id));
create table login_apple (id bigint generated by default as identity, apple_id varchar(255), token varchar(255), primary key (id));
create table login_google (id bigint generated by default as identity, google_id varchar(255), token varchar(255), primary key (id));
create table ponto_coleta (id bigint generated by default as identity, contato varchar(255), descricao varchar(255), horario_funcionamento varchar(255), nome varchar(255), primary key (id));
create table relatorio_poluicao (criado_em timestamp(6), id bigint generated by default as identity, localizacao_id bigint unique, tipo_poluicao varchar(255), primary key (id));
create table tb_documentos (id bigint generated by default as identity, cpf varchar(255), rg varchar(255), primary key (id));
create table usuario (id bigint generated by default as identity, nome_completo varchar(255), primary key (id));
alter table if exists cadastrar add constraint FKamt0upm8b7rhbixwxrjv4algj foreign key (documentos_id) references tb_documentos;
alter table if exists cadastrar add constraint FKmw461iwrvbxtsrhi6ges50j07 foreign key (usuario_id) references usuario;
alter table if exists eventos add constraint FKpvjmg96ol6rh3wxmwg776v6au foreign key (localizacao_id) references localizacao;
alter table if exists eventos add constraint FKh1h7x29wfjquom85fq8pipfxo foreign key (organizador_id) references usuario;
alter table if exists eventos add constraint FKgkipisolbv8t34m08gbdgautc foreign key (ponto_coleta_id) references ponto_coleta;
alter table if exists eventos_participantes add constraint FKaexl8grwnwo4k6yobtgk5h0rf foreign key (participantes_id) references usuario;
alter table if exists eventos_participantes add constraint FKq7ep0f3cniv1k80j3tm9dk4d foreign key (eventos_id) references eventos;
alter table if exists localizacao add constraint FKf7pcd0wjkqieljs48w1pmgifi foreign key (reportado_por_id) references usuario;
alter table if exists login add constraint FKdjkhg132oavpve1w1kuua6fq foreign key (cadastrar_id) references cadastrar;
alter table if exists login add constraint FKc7cfh2n8udej2qk26ede1cnrd foreign key (esqueci_senha_id) references esqueci_senha;
alter table if exists login add constraint FKdgq882cqtbpl9uqn3v2yq4n02 foreign key (login_apple_id) references login_apple;
alter table if exists login add constraint FKrchmtuwp6pkh4sj2fcyvfy8om foreign key (login_google_id) references login_google;
alter table if exists relatorio_poluicao add constraint FKi3ok2canbtysxg6oobfhtf9ai foreign key (localizacao_id) references localizacao;
