create table tb_vmar_cadastrar (documentos_id number(19,0), id number(19,0) generated as identity, usuario_id number(19,0), email varchar2(255 char), nome_usuario varchar2(255 char), senha varchar2(255 char), primary key (id));
create table tb_vmar_cadastrar_cnpj (id number(19,0) generated as identity, cnpj varchar2(255 char), razao_social varchar2(255 char), primary key (id));
create table tb_vmar_contato (id number(19,0) generated as identity, celular varchar2(255 char), email_alternativo varchar2(255 char), telefone varchar2(255 char), primary key (id));
create table tb_vmar_documentos (id number(19,0) generated as identity, cpf varchar2(255 char), rg varchar2(255 char), primary key (id));
create table tb_vmar_endereco (numero number(10,0) not null check (numero>=1), id number(19,0) generated as identity, bairro varchar2(255 char), cep varchar2(255 char), cidade varchar2(255 char), complemento varchar2(255 char), estado varchar2(255 char), logradouro varchar2(255 char), primary key (id));
create table tb_vmar_esqueci_senha (id number(19,0) generated as identity, codigo_recuperacao varchar2(255 char), email varchar2(255 char), nova_senha varchar2(255 char), primary key (id));
create table tb_vmar_eventos (data_hora timestamp(6), id number(19,0) generated as identity, localizacao_id number(19,0) unique, organizador_id number(19,0), ponto_coleta_id number(19,0) unique, descricao varchar2(255 char), nome varchar2(255 char), primary key (id));
create table tb_vmar_eventos_participantes (participantes_id number(19,0) not null, tb_vmar_eventos_id number(19,0) not null);
create table tb_vmar_localizacao (id number(19,0) generated as identity, reportado_em timestamp(6), reportado_por_id number(19,0), descricao varchar2(255 char), endereco varchar2(255 char), referencia varchar2(255 char), url_foto varchar2(255 char), primary key (id));
create table tb_vmar_login (cadastrar_id number(19,0) unique, esqueci_senha_id number(19,0) unique, id number(19,0) generated as identity, login_apple_id number(19,0) unique, login_google_id number(19,0) unique, nome_usuario varchar2(255 char), senha varchar2(255 char), primary key (id));
create table tb_vmar_login_apple (id number(19,0) generated as identity, apple_id varchar2(255 char), token varchar2(255 char), primary key (id));
create table tb_vmar_login_google (id number(19,0) generated as identity, google_id varchar2(255 char), token varchar2(255 char), primary key (id));
create table tb_vmar_ponto_coleta (id number(19,0) generated as identity, contato varchar2(255 char), descricao varchar2(255 char), horario_funcionamento varchar2(255 char), nome varchar2(255 char), primary key (id));
create table tb_vmar_relatorio_poluicao (criado_em timestamp(6), id number(19,0) generated as identity, localizacao_id number(19,0) unique, tipo_poluicao varchar2(255 char), primary key (id));
create table tb_vmar_usuario (id number(19,0) generated as identity, nome_completo varchar2(255 char), primary key (id));
alter table tb_vmar_cadastrar add constraint FK29xfqxims9ncaef3x93x6g6to foreign key (documentos_id) references tb_vmar_documentos;
alter table tb_vmar_cadastrar add constraint FKcifoax19ont7gac54vwa3eyq0 foreign key (usuario_id) references tb_v
mar_usuario;
alter table tb_vmar_eventos add constraint FKs6mmbq48q1mi7ak1gexopaakd foreign key (localizacao_id) references tb_vmar_localizacao;
alter table tb_vmar_eventos add constraint FKej5rv5cb0e83f54dxmhp829mo foreign key (organizador_id) references tb_vmar_usuario;
alter table tb_vmar_eventos add constraint FKpo9ghujurvwjw9r97vbs5eke5 foreign key (ponto_coleta_id) references tb_vmar_ponto_coleta;
alter table tb_vmar_eventos_participantes add constraint FK9w4nmjwsxlx0v06fshw0i5rrr foreign key (participantes_id) references tb_vmar_usuario;
alter table tb_vmar_eventos_participantes add constraint FKfdv6autg8wc7772iruudgs0oe foreign key (tb_vmar_eventos_id) references tb_vmar_eventos;
alter table tb_vmar_localizacao add constraint FKpu6bn6nkqunnitypfq6ctbal7 foreign key (reportado_por_id) references tb_vmar_usuario;
alter table tb_vmar_login add constraint FK51cnqwwy115tova4j0cpolxt4 foreign key (cadastrar_id) references tb_vmar_cadastrar;
alter table tb_vmar_login add constraint FKlqrax2k4nwhor42cjeejagk1u foreign key (esqueci_senha_id) references tb_vmar_esqueci_senha;
alter table tb_vmar_login add constraint FKgv10ldfdnw9rgydq7qwi7fglu foreign key (login_apple_id) references tb_vmar_login_apple;
alter table tb_vmar_login add constraint FKh05jq29m9f0y5jbe49r7xx3pt foreign key (login_google_id) references tb_vmar_login_google;
alter table tb_vmar_relatorio_poluicao add constraint FKfbah7vqch4asuyssp9a8loffe foreign key (localizacao_id) references tb_vmar_localizacao;
