version: '3.8'

services:
  verdemar:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=target/verdemar-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_ENV=production
      - DB_URL=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
      - DB_USER=rm99097
      - DB_PASS=110590
    restart: always
    user: appuser
    container_name: verdemar_app
    networks:
      - verdemar_network
    volumes:
      - verdemar_data:/app/data

networks:
  verdemar_network:
    driver: bridge

volumes:
  verdemar_data: